<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('payroll_run_adjustments', function (Blueprint $table) {
            if (! Schema::hasColumn('payroll_run_adjustments', 'loan_id')) {
                // Set only for adjustments auto-generated by LoanRepaymentService.
                // Manual/ad-hoc adjustments (including a manually-picked "Loan
                // Repayment" rule from the assignment picker) leave this null —
                // they are not traced back to a specific loan's balance.
                $table->foreignId('loan_id')->nullable()->after('payroll_rule_id')
                    ->constrained('loans')->nullOnDelete();
            }
        });
    }

    public function down(): void
    {
        Schema::table('payroll_run_adjustments', function (Blueprint $table) {
            if (Schema::hasColumn('payroll_run_adjustments', 'loan_id')) {
                $table->dropConstrainedForeignId('loan_id');
            }
        });
    }
};
